version: "3.9"

services:
  devopsdb:
    image: jayaprakashdevops/dockerwebapp:appimage
    ports:
      - "1111:3306"
    deploy:
      replicas: 3
    networks:
      - mynetwork

  application:
    image: jayaprakashdevops/dockerwebapp:dbimage
    ports:
      - "1234:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
