version: "3.9"

services:
  dockerapp:
    image: ./Docker-db
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    build: ./Docker-app
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
